export const currencyLocaleMap: { [key: string]: string } = {
  USD: 'en-us',
  ARS: 'es-ar',
  EUR: 'de',
  GBP: 'en-gb',
  JPY: 'ja',
  AUD: 'en-au',
  CAD: 'en-ca',
  KRW: 'ko',
  PLN: 'pl',
  SGD: 'zh-sg',
  TWD: 'zh-tw',
  CZK: 'cs',
  UAH: 'ua',
  BYN: 'be',
  KZT: 'kk',
  MXN: 'es-mx',
  BRL: 'pt-br',
  COP: 'es-co',
};
